# Generated by Django 6.0.5 on 2026-07-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
